config/routes.rb
Rails.application.routes.draw do
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  namespace :admin do
    resources :users do
      post :import, on: :collection
    end
  end
  
  root to: 'tasks#index'
  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :name, presence: true, length: { maximum: 30 }
  validates :activity_at, presence: true
  belongs_to :user
  has_one_attached :image
  scope :recent, -> { order(activity_at: :desc) }

  def self.ransackable_attributes(auth_object = nil)
    %w[name activity_at]
  end

  def self.ransackable_associations(auth_object = nil)
    []
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  has_many :tasks
  scope :recent, -> { order(:created_at) }

  def self.csv_attributes
    ["name", "email", "password_digest", "created_at", "updated_at"]
  end

  def self.generate_csv
    CSV.generate(headers: true) do |csv|
      csv << csv_attributes
      all.each do |user|
        csv << csv_attributes.map{|attr| user.send(attr) }
      end
    end
  end

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      user = new
      user.attributes = row.to_hash.slice(*csv_attributes)
      user.save!
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :login_required, except: [:new, :create]
  before_action :admin_login_required, only: [:index, :destroy]
  before_action :correct_user, only: [:edit, :update]

  def index
    @q = User.ransack(params[:q])
    @users = @q.result(distinct: true).page(params[:page]).per(15).recent

    respond_to do |format|
      format.html
      format.csv { send_data @users.generate_csv, filename: "users-#{Time.zone.now.strftime('%Y%m%d%S')}.csv"}
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)

    if current_user&.admin? && @user.save
      redirect_to admin_user_path(@user), notice: "ユーザー「#{@user.name}」を登録しました。"
    elsif current_user
      if current_user&.admin?
        render :new
      else
        redirect_to root_path, notice: '権限がありません。'
      end
    elsif @user.save
      log_in @user
      redirect_to root_path, notice: "ユーザー「#{@user.name}」を登録しました。"
    else
      render :new
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to admin_user_path(@user), notice: "ユーザー「#{@user.name}」を更新しました。"
    else
      render :new
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_url, notice: "ユーザー「#{@user.name}」を削除しました。"
  end

  def import
    User.import(params[:file])
    redirect_to admin_users_url, notice: "ユーザーを追加しました。"
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def admin_login_required
    redirect_to tasks_path, notice: '権限がありません。' unless current_user.admin?
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to root_path, notice: '権限がありません。' unless @user == current_user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  include SessionsHelper

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def login_required
    redirect_to login_path, notice: 'ログインが必要です。' unless current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: session_params[:email])

    if user&.authenticate(session_params[:password])
      log_in user
      redirect_to root_path, notice: 'ログインしました。'
    else
      @error_message = 'メールアドレスまたはパスワードが間違っています'
      render :new
    end
  end

  def destroy
    reset_session
    redirect_to root_path, notice: 'ログアウトしました。'
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :login_required, only: [:create, :edit, :update, :destroy]

  def index
    if current_user
      @q = current_user.tasks.ransack(params[:q])
      @tasks = @q.result(distinct: true).page(params[:page]).recent.per(10)
    else
      @q = Task.all.ransack(params[:q])
      @tasks = @q.result(distinct: true).page(params[:page]).recent.per(10)
    end
  end

  def show
  end

  def new
    @task = Task.new
  end

  def edit
  end

  def update
    @task.update!(task_params)
    redirect_to tasks_url, notice: "トレーニング「#{@task.name}」を更新しました。"
  end

  def destroy
    @task.destroy
  end

  def create
    @task = current_user.tasks.new(task_params)

    if @task.save
      redirect_to @task, notice: "トレーニング 「#{@task.name}」を登録しました。"
    else
      render :new
    end
  end

  private

  def task_params
    params.require(:task).permit(:name, :activity_at, :weight, :lep, :set, :description, :image)
  end

  def set_task
    if current_user
      @task = current_user.tasks.find(params[:id])
    else
      @task = Task.find(params[:id])
    end
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user?(user)
    user == current_user
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/admin/users/_form.html.slim
- if user.errors.present?
  ul#error_explanation
    - user.errors.full_messages.each do |message|
      li= message

= form_with model: [:admin, user], local: true do |f|
  .form-group
    = f.label :name, '名前'
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :email, 'メールアドレス'
    = f.text_field :email, class: 'form-control'
  .form-group
    = f.label :password, 'パスワード'
    = f.password_field :password, class: 'form-control'
  .form-group
    = f.label :password_confirmation, 'パスワード(確認)'
    = f.password_field :password_confirmation, class: 'form-control'
  = f.submit '登録する', class: 'btn btn-primary'

app/views/admin/users/edit.html.slim
h1 ユーザーの編集

- if current_user&.admin?
  .nav.justify-content-end
    = link_to '一覧', admin_users_path, class: 'nav-link'

= render partial: 'form', locals: { user: @user }

app/views/admin/users/index.html.slim
h1.mb-4 ユーザー一覧

= search_form_for [:admin, @q], class: 'mb-5' do |f|
  .form-group.row
    = f.label :name_cont, 'ユーザー名', class: 'col-sm-2 col-form-label'
    .col-sm-10
      = f.search_field :name_cont, class: 'form-control', placeholder: 'ユーザー名を入力してください'
  .form-group.row
    = f.label :created_at_gteq, '登録日時', class: 'col-sm-2 col-form-label'
    .col-sm-10
      = f.search_field :created_at_gteq, class: 'form-control', placeholder: '例: 2020-01-01 00:00'
  .form-group
    = f.submit class: 'btn btn-outline-primary'

= link_to '新規登録', new_admin_user_path, class: 'btn btn-primary mb-3'
= link_to 'CSVエクスポート', admin_users_path(format: :csv), class: 'btn btn-primary ml-3 mb-3'

= form_tag import_admin_users_path, multipart: true, class: 'mb-3' do
 = file_field_tag :file
 = submit_tag "CSVインポート", class: 'btn btn-primary'

.mb-3
  = paginate @users
  = page_entries_info @users, entry_name: 'ユーザー'

.mb-3
table.table.table-hover
  thead.thead-default
    tr
      th= sort_link([:admin, @q], :name, [:name, "created_at desc"])
      th= User.human_attribute_name(:email)
      th= User.human_attribute_name(:admin)
      th= User.human_attribute_name(:created_at)
      th= User.human_attribute_name(:updated_at)
      th
  tbody
    - @users.each do |user|
      tr
        td= link_to user.name, [:admin, user]
        td= user.email
        td= user.admin? ? 'あり' : 'なし'
        td= l user.created_at
        td= l user.updated_at
        - if current_user.admin? && !current_user?(user)
          td
            = link_to '削除', [:admin, user], method: :delete, data: { confirm: "ユーザー「#{user.name}」を削除します。よろしいですか？" }, class: 'btn btn-danger'

app/views/admin/users/new.html.slim
h1 ユーザー登録

= render partial: 'form', locals: { user: @user }

app/views/admin/users/show.html.slim
h1.mb-4 ユーザーの詳細

- if current_user&.admin?
  .nav.justify-content-end
    = link_to '一覧', admin_users_path, class: 'nav-link'
table.table.table-hover
  tbody
    tr
      th= User.human_attribute_name(:name)
      td= @user.name
    tr
      th= User.human_attribute_name(:email)
      td= @user.email
    - if current_user&.admin?
      tr
        th= User.human_attribute_name(:admin)
        td= @user.admin? ? 'あり' : 'なし'

- if current_user
  = link_to '編集', edit_admin_user_path, class: 'btn btn-primary mr-3'

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | WorkoutDiary
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body data-turbolinks="false"
    .app-title.navbar.navbar-expand-md.navbar-dark.bg-primary.mb-4
      .navbar-brand= link_to 'WorkoutDiary', tasks_path, class: 'navbar-brand'
      ul.navbar-nav.ml-auto
          li.nav-item= link_to current_user.name, admin_user_path(current_user.id), class: 'nav-link' if current_user
          li.nav-item= link_to 'トレーニング一覧', tasks_path, class: 'nav-link'
          li.nav-item= link_to '新規登録', new_admin_user_path, class: 'nav-link' unless current_user
          li.nav-item= link_to 'ユーザー一覧', admin_users_path, class: 'nav-link' if current_user&.admin?
          - if current_user
            li.nav-item= link_to 'ログアウト', logout_path, method: :delete, class: 'nav-link'
          - else
            li.nav-item= link_to 'ログイン', login_path, class: 'nav-link'
    .container.wrapper
      - if flash.notice.present?
        .alert.alert-success= flash.notice
      = yield
    footer.footer.mt-5
      .container.text-center.mb-4
        |  Created by KAZUKI TOYODA

app/views/tasks/_form.html.slim
= form_with model: task, local: true do |f|
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control', id: 'task_name'
  .form-group
    = f.label :activity_at 
    .input-group date-target-input='nearest'
      = f.text_field :activity_at, class: 'form-control datetimepicker-input', id: 'activity_at', data: {target: '#activity_at'}
      .input-group-append data-target="#activity_at" data-toggle="datetimepicker"
        .input-group-text
          i.fa.fa-calendar
  .form-inline.mb-3
    .form-group
    = f.label '記録', class: 'mr-sm-2'
    = f.number_field :weight, step: '0.1', class: 'form-control mr-sm-2', id: 'task_weight', placeholder: '重量'
    = f.label 'kg', class: 'mr-sm-2'  
    = f.number_field :lep, class: 'form-control mr-sm-2', id: 'task_lep', placeholder: '回数'
    = f.label '回', class: 'mr-sm-2'
    = f.number_field :set, class: 'form-control mr-sm-2', id: 'task_set', placeholder: 'セット数'
    = f.label 'セット', class: 'mr-sm-2'
  .form-group
    = f.label :description
    = f.text_area :description, rows: 5, class: 'form-control', id: 'task_description'
  .form-group
    = f.label :image, accept: "image/png, image/jpeg, image/gif"
    = f.file_field :image, class: 'form-control'
  = f.submit nil, class: 'btn btn-primary'

app/views/tasks/destroy.js.erb
document.querySelector("#task-<%= @task.id %>").style.display = 'none';

var message = document.createElement('p');
message.innerText = 'トレーニング「<%= @task.name %>」を削除しました。残りのトレーニングは<%= Task.count %>件です。';
document.querySelector('table').insertAdjacentElement('beforebegin', message);

app/views/tasks/edit.html.slim
h1 トレーニングの編集

.nav.justify-content-end
  = link_to '一覧', tasks_path, class: 'nav-link'

- if @task.errors.present?
  ul#error_explanation
    - @task.errors.full_messages.each do |message|
      li= message

= render partial: 'form', locals: { task: @task }

app/views/tasks/index.html.slim
h1.mb-4 トレーニング一覧

= search_form_for @q, class: 'mb-5' do |f|
  .form-group.row
    = f.label :name_cont, 'トレーニング名', class: 'col-sm-2 col-form-label'
    .col-sm-10
      = f.search_field :name_cont, class: 'form-control', placeholder: 'トレーニング名を入力してください'
  .form-group.row
    = f.label :activity_at_gteq, '実施日', class: 'col-sm-2 col-form-label'
    .col-sm-10
      = f.search_field :activity_at_gteq, class: 'form-control', placeholder: '例: 2020-01-01 00:00'
  .form-group
    = f.submit class: 'btn btn-outline-primary'

- if current_user
  = link_to '新規登録', new_task_path, class: 'btn btn-primary mb-3'

.mb-3
  = paginate @tasks
  = page_entries_info @tasks, entry_name: 'トレーニング'

table.table.table-hover
  thead.thead-default
    tr
      th= sort_link(@q, :name, [:name, "activity_at desc"])
      th= Task.human_attribute_name(:activity_at)
      th
  tbody
    - @tasks.each do |task|
      tr id="task-#{task.id}"
        td= link_to task.name, task
        td= l task.activity_at
        - if current_user&.admin? || current_user
          td
            = link_to '編集', edit_task_path(task), class: 'btn btn-primary mr-3'
            = link_to '削除', task, method: :delete, remote: true, data: { confirm: "トレーニング「#{task.name}」を削除します。よろしいですか？" }, class: 'btn btn-danger delete'

#calendar

app/views/tasks/new.html.slim
h1 トレーニングの新規登録

.nav.justify-content-end
  = link_to '一覧', tasks_path, class: 'nav-link'

- if @task.errors.present?
  ul#error_explanation
    - @task.errors.full_messages.each do |message|
      li= message

= render partial: 'form', locals: { task: @task }

app/views/tasks/show.html.slim
h1.mb-4 トレーニング詳細

.nav.justify-content-end
  = link_to '一覧', tasks_path, class: 'nav-link'
table.table.table-hover
  tbody
    tr
      th= Task.human_attribute_name(:name)
      td= @task.name
    tr
      th= Task.human_attribute_name(:activity_at)
      td= l @task.activity_at
    tr
      th= '記録'
      td= "#{@task.weight}kg #{@task.lep}回 #{@task.set}セット" if @task.weight
    tr
      th= Task.human_attribute_name(:description)
      td= auto_link(simple_format(h(@task.description), {}, sanitize: false, wrapper_tag: "div"))
    tr
      th= Task.human_attribute_name(:image)
      td= image_tag @task.image.variant(resize:'400x400').processed if @task.image.attached?

- if current_user&.admin? || current_user
  = link_to '編集', edit_task_path, class: 'btn btn-primary mr-3'